CWD=$(shell pwd)
MOCHA=node_modules/.bin/mocha
ISTANBUL=node_modules/.bin/istanbul
COVERALLS=node_modules/coveralls/bin/coveralls.js
TEST_FILES=$(shell find test/*.js) 
LINKEDIN_API_KEY=77znf4cik69ira
LINKEDIN_SECRET_KEY=e2KnFfFKwX4eJ2Xd 
LINKEDIN_OAUTH_USER_TOKEN=5fd26c6f-55bc-4005-9459-f1376e9c6cc7
LINKEDIN_OAUTH_USER_SECRET=1088c2af-eb93-4b93-84c9-38262ba7656c

test:
	NODE_PATH=./ \
	DEBUG=hh-api \
	LINKEDIN_API_KEY=$(LINKEDIN_API_KEY) \
  $(MOCHA) -R spec $(TEST_FILES)
up:
	NODE_PATH=./ \
	DEBUG=hh-api \
	LINKEDIN_API_KEY=$(LINKEDIN_API_KEY) \
	LINKEDIN_SECRET_KEY=$(LINKEDIN_API_KEY) \
	LINKEDIN_OAUTH_USER_TOKEN=$(LINKEDIN_OAUTH_USER_TOKEN) \
	LINKEDIN_OAUTH_USER_SECRET=$(LINKEDIN_OAUTH_USER_SECRET) \
	node app.js
	
.PHONY: up test
